version: '3.9'
services:
  postgresql:
    image: postgres:latest
    container_name: postgresql
    hostname: postgresql
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: test
      POSTGRES_DB: test
      TZ: Asia/Tokyo
    ports:
      - 5432:5432
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
      - ./postgresql/etc:/etc/postgresql
      - ./postgresql/wal_archive:/var/lib/postgresql/archive
    command: postgres -c config_file=/etc/postgresql/postgresql.conf -c hba_file=/etc/postgresql/pg_hba.conf
    tty: true
    stdin_open: true
    networks:
      - cicd
  tomcat:
    image: tomcat:latest
    container_name: postgresql
    hostname: tomcat
    restart: always
    environment:
      TZ: Asia/Tokyo
    ports:
      - 8080:8080
    volumes:
      - ./tomcat/webapps:/usr/local/tomcat/webapps
    
networks:
  cicd:
    name: cicd
