#!/bin/bash

FILENAME='src/src/environment.js'

function bkupFileContent(){
    FILE_CONTENT=()
    IFS_BKUP=$IFS
    IFS=$'\n'
    for line in `cat ${FILENAME}`; do
        FILE_CONTENT+=("$line")
    done
    IFS=$IFS_BKUP
}

function deletePrivateInfoAndGitAdd(){
    sed -i "s/\'.*\'/\'\'/g" $FILENAME
    git add .
}

function restoreFileContent(){
    rm $FILENAME
    for((i=0; i < ${#FILE_CONTENT[@]}; i++)); do
        echo ${result[i]} >> $FILENAME
    done
}

function main(){
    bkupFileContent
    deletePrivateInfoAndGitAdd
    restoreFileContent
}

main
