#!/bin/bash

URL="https://github.com/tuimac/Tools.git"

[[ ! -e .git ]] && git init

if [ "$1" = "" ]; then
    echo -e "Select files.\nExit."
    exit 1
fi
#    echo -en "Add all files to repository.\nIs that OK?[Y/N]> "
#    read ANSWER
#    [[ ! $ANSWER = "Y" ]] && { exit 1; }
#    git add .
#else
#    git add "$1"
#fi

echo -en "Comment below\n> "
read COMMENT

#git rm -r --cached .
git add .
git commit -m "${COMMENT}"
git remote add origin "${URL}"
git pull origin master
git push -u origin master

#echo -en "Type in branch(Empty is master)\n> "
#read BRANCH
#[[ $BRANCH == "" ]] && BRANCH="master"
#git push -u origin "${BRANCH}"
