#!/bin/bash

URL="https://github.com/tuimac/tools.git"

EMAIL=`git config --global --get user.email`
USERNAME=`git config --global --get user.name`

[[ $EMAIL = "" ]] && git config --global user.email 'tuimac.devadm01@gmail.com'
[[ $USERNAME = "" ]] && git config --global user.name 'tuimac'

[[ ! -e .git ]] && git init
[[ "$1" = "" ]] && { echo -e "Select files.\nExit."; exit 1; }
#    echo -en "Add all files to repository.\nIs that OK?[Y/N]> "
#    read ANSWER
#    [[ ! $ANSWER = "Y" ]] && { exit 1; }
#    git add .
#else
#    git add "$1"
#fi

#echo -en "Comment below\n> "
#read COMMENT

COMMENT="upload"

#git reset --hard "${URL}" master
#git rm -r --cached .
git add .
git commit -m "${COMMENT}"
git remote add origin "${URL}"
git pull origin master
git push -u origin master

#echo -en "Type in branch(Empty is master)\n> "
#read BRANCH
#[[ $BRANCH == "" ]] && BRANCH="master"
#git push -u origin "${BRANCH}"
