#!/bin/bash

function connectionList(){
    aws ssm describe-instance-information | jq -r '.InstanceInformationList[] | [.Name, .InstanceId] | @tsv'
}

function connectToSession(){
    local username=`echo $1 | awk -F '@' '{print $1}'`
    local hostname=`echo $1 | awk -F '@' '{print $2}'`
    # Search the target instance ID
    local instanceId=`aws ssm describe-instance-information | jq -r --arg hostname "$hostname" '.InstanceInformationList[] | select(.Name==$hostname) | .InstanceId'`
    # Connect to the target host
    aws ssm start-session --target ${instanceId} --document-name AWS-StartInteractiveCommand --parameters command='sudo su - '${username}
}

function userguide(){
    echo -e "usage: connect [start <user>@<session name> | list ]"
    echo -e "
optional arguments:
start           Start the connection to the target host.
list            List the available connections.
"

}

function main(){
    case $1 in
        'start')
            [[ ! "$2" =~ [.*@.*] ]] && { userguide; exit 1; }
            connectToSession $2;;
        'list')
            connectionList;;
        *)
            userguide
            exit 1;;
    esac
}

main $1 $2
