#!/bin/bash

function connectionList(){
    aws ssm describe-instance-information | jq -r '.InstanceInformationList[] | [.Name, .InstanceId] | @tsv'
}

function connectToSession(){
    local hostname=$1
    local username=
    # Search the target instance ID
    local instanceId=`aws ssm describe-instance-information | jq -r --arg hostname "$hostname" '.InstanceInformationList[] | select(.Name==$hostname) | .InstanceId'`
    # Connect to the target host
    aws ssm start-session --target ${instanceId} --document-name AWS-StartInteractiveCommand --parameters command='sudo su - '${username}
}

function userguide(){
    echo -e "usage: connect [start | list ]"
    echo -e "
optional arguments:
start          Install 389 Directory Service into your server.
client-install          Install SSSD into your server.
"

}

function main(){
    case $1 in
        'start')
            [[ ! "$2" =~ [.*@.*] ]] && { userguide; exit 1; }
            connectToSession $2;;
        'list')
            connectionList;;
        *)
            userguide
            exit 1;;
    esac
}

main $1 $2
