services:
  keycloak:
    image: keycloak/keycloak:latest
    container_name: keycloak
    hostname: keycloak
    ports:
      - 8000:8080
    networks:
      - keycloak
    restart: always
    volumes:
      - keycloak:/opt/keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=P@ssw0rd
    command: start-dev

volumes:
  keycloak:

networks:
  keycloak:
    name: keycloak