AWSTemplateFormatVersion: 2010-09-09
Description: Create RedHat Enterprise Linux HA/DR environment

Parameters:
  VpcCidr:
    Type: String
    Default: 10.0.0.0/27

  SubnetACidr:
    Type: String
    Default: 10.0.0.0/28

  SubnetBCidr:
    Type: String
    Default: 10.0.0.16/28

  PrimaryIP:
    Type: String
    Default: 10.0.0.4

  SecondaryIP:
    Type: String
    Default: 10.0.0.20

  AMIID:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2

  SSHPemFilename:
    Type: String
    Default: tuimac

  TagKey:
    Type: String
    Default: Name

  TagValue:
    Type: String
    Default: Pacemaker

Resources:
  # VPC
  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
      Tags:
        - Key: !Ref TagKey
          Value: !Ref TagValue
 
  # Internet Gateway
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: !Ref TagKey
          Value: !Ref TagValue

  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref Vpc

  # Subnet
  SubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref Vpc
      CidrBlock: !Ref SubnetACidr
      AvailabilityZone: ap-northeast-3a
      MapPublicIpOnLaunch: true
      Tags:
        - Key: !Ref TagKey
          Value: !Ref TagValue

  SubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref Vpc
      CidrBlock: !Ref SubnetBCidr
      AvailabilityZone: ap-northeast-3b
      MapPublicIpOnLaunch: true
      Tags:
        - Key: !Ref TagKey
          Value: !Ref TagValue

  # RouteTable
  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref Vpc
      Tags:
        - Key: !Ref TagKey
          Value: !Ref TagValue

  InternetRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  RouteTableAccociationA:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTable
      SubnetId: !Ref SubnetA

  RouteTableAccociationB:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTable
      SubnetId: !Ref SubnetB

  # Security Group
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Ref TagValue
      GroupDescription: for test
      VpcId: !Ref Vpc
      SecurityGroupIngress:
        - IpProtocol: -1
          CidrIp: !Ref VpcCidr
          Description: ANY
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
          Description: ANY
      Tags:
        - Key: !Ref TagKey
          Value: !Ref TagValue

  # Endpoint
  S3Endpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PolicyDocument: '{
        "Version": "2012-10-17",
        "Statement":[{
          "Effect": "Allow",
          "Principal": "*",
          "Action": "*",
          "Resource": "*"
        }]
      }'
      RouteTableIds:
        - !Ref RouteTable
      ServiceName: !Sub com.amazonaws.${AWS::Region}.s3
      VpcId: !Ref Vpc

  EC2InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: EC2InstanceRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: EC2InstancePolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "ec2:*"
                Resource:
                  - "*"
      Tags:
        - Key: !Ref TagKey
          Value: !Ref TagValue

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref EC2InstanceRole

  # EC2 Instance
  Primary:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref AMIID
      InstanceType: t3.small
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeleteOnTermination: true
          Description: Primary Server ENI
          GroupSet:
            - !Ref SecurityGroup
          SubnetId: !Ref SubnetA
          DeviceIndex: 0
          PrivateIpAddress: !Ref PrimaryIP
      IamInstanceProfile: !Ref EC2InstanceProfile
      SourceDestCheck: false
      KeyName: !Ref SSHPemFilename
      Tags:
        - Key: Name
          Value: primary
      UserData:
        Fn::Base64: !Sub
          - |
            #!/bin/bash
            LOG=/var/log/user-data.log
            touch $LOG
            exec >> $LOG 2>&1
                yum update -y
                yum install -y docker git
                mkdir -p /etc/vim/undo
                mkdir -p /etc/vim/backup
                rm /etc/vimrc
                curl -L https://raw.githubusercontent.com/tuimac/tools/master/vim/vimrc -o /etc/vimrc
                chmod -R 777 /etc/vim
                echo 'if [ -n "$BASH_VERSION" -o -n "$KSH_VERSION" -o -n "$ZSH_VERSION" ]; then
                  [ -x /usr/bin/id ] || return
                  ID=`/usr/bin/id -u`
                  #[ -n "$ID" -a "$ID" -le 200 ] && return
                  # for bash and zsh, only if no alias is already set
                  alias vi >/dev/null 2>&1 || alias vi=vim
                fi' > /etc/profile.d/vim.sh
                systemctl enable docker
                systemctl start docker
                usermod -aG docker ec2-user
                echo ${PrimaryIP}' primary' >> /etc/hosts
                echo ${SecondaryIP}' secondary' >> /etc/hosts
                echo 'primary' > /etc/hostname
                yum install -y pacemaker pcs
                echo "password" | passwd --stdin hacluster
                cd /home/ec2-user
                git clone https://github.com/tuimac/tools.git; echo "cloned"
                chown ec2-user:ec2-user -R /home/ec2-user/tools
                su ec2-user
                git config --global user.email 'tuimac.devadm01@gmail.com'
                git config --global user.name 'tuimac'
                reboot
          - {
              PRIMARYIP: !Ref PrimaryIP,
              SECONDARYIP: !Ref SecondaryIP
            }

  Secondary:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref AMIID
      InstanceType: t3.small
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeleteOnTermination: true
          Description: Secondary Server ENI
          GroupSet:
            - !Ref SecurityGroup
          SubnetId: !Ref SubnetB
          DeviceIndex: 0
          PrivateIpAddress: !Ref SecondaryIP
      IamInstanceProfile: !Ref EC2InstanceProfile
      SourceDestCheck: false
      KeyName: !Ref SSHPemFilename
      Tags:
        - Key: Name
          Value: secondary
      UserData:
        Fn::Base64: !Sub
          - |
            #!/bin/bash
            LOG=/var/log/user-data.log
            touch $LOG
            exec >> $LOG 2>&1
                yum update -y
                yum install -y docker git
                mkdir -p /etc/vim/undo
                mkdir -p /etc/vim/backup
                rm /etc/vimrc
                curl -L https://raw.githubusercontent.com/tuimac/tools/master/vim/vimrc -o /etc/vimrc
                chmod -R 777 /etc/vim
                echo 'if [ -n "$BASH_VERSION" -o -n "$KSH_VERSION" -o -n "$ZSH_VERSION" ]; then
                  [ -x /usr/bin/id ] || return
                  ID=`/usr/bin/id -u`
                  #[ -n "$ID" -a "$ID" -le 200 ] && return
                  # for bash and zsh, only if no alias is already set
                  alias vi >/dev/null 2>&1 || alias vi=vim
                fi' > /etc/profile.d/vim.sh
                systemctl enable docker
                systemctl start docker
                usermod -aG docker ec2-user
                echo ${PrimaryIP}' primary' >> /etc/hosts
                echo ${SecondaryIP}' secondary' >> /etc/hosts
                echo 'secondary' > /etc/hostname
                yum install -y pacemaker pcs
                echo "password" | passwd --stdin hacluster
                cd /home/ec2-user
                git clone https://github.com/tuimac/tools.git; echo "cloned"
                chown ec2-user:ec2-user -R /home/ec2-user/tools
                su ec2-user
                git config --global user.email 'tuimac.devadm01@gmail.com'
                git config --global user.name 'tuimac'
                reboot
          - {
              PRIMARYIP: !Ref PrimaryIP,
              SECONDARYIP: !Ref SecondaryIP
            }

