AWSTemplateFormatVersion: 2010-09-09
Description: Create Auto Start/Stop EC2 instance environment
Parameters:
  VPNTagValue:
    Type: String

Resources:
  #Prefix List
  VPNDNSPrefixList:
    Type: AWS::EC2::PrefixList
    Properties:
      AddressFamily: IPv4
      Entries:
        - Cidr: !Sub
            - "${IP}/32"
            - IP: !Ref VPNDNSPrimary
          Description: VPN Server IP 
        - Cidr: 8.8.8.8/32
          Description: Google Public Primary DNS IP 
        - Cidr: 9.9.9.9/32
          Description: Google Public Secondary DNS IP 
      MaxEntries: 10
      PrefixListName: VPN-DNS
      Tags:
        - Key: !Ref VPNTagKey
          Value: !Ref VPNTagValue
        - Key: Name
          Value: VPN-DNS

Outputs:
  VPNPublicRouteTableDId:
    Value: !Ref VPNPublicRouteTableD
    Export:
      Name: VPNPublicRouteTableDId

  VPNDNSPrefixListId:
    Value: !GetAtt VPNDNSPrefixList.PrefixListId
