# https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta2
apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
nodeRegistration:
  name: docker
localAPIEndpoint:
  bindPort: 6443

---

apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
clusterName: production
controlPlaneEndpoint: docker.tuimac.private:6443
apiServer:
  extraArgs:
    enable-admission-plugins: DefaultTolerationSeconds
    default-not-ready-toleration-seconds: "10"
    default-unreachable-toleration-seconds: "10"
networking:
  podSubnet: 10.230.0.0/16
  serviceSubnet: 10.231.0.0/16
  dnsDomain: prod.local
certificatesDir: /etc/kubernetes/pki
