version: '3.9'
services:
  gitlab:
    image: gitlab/gitlab-ee:latest
    container_name: gitlab
    hostname: gitlab
    restart: always
    environment:
      TZ: Asia/Tokyo
    ports:
      - 8000:80
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab
    networks:
      - gitlab
  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    hostname: gitlab-runner
    restart: always
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./gitlab-runner/config:/etc/gitlab-runner
    networks:
      - gitlab
networks:
  gitlab:
    name: gitlab
