apiVersion: v1
kind: Service
metadata:
  name: dev-service
spec:
  selector:
    app: dev
  type: NodePort
  ports:
    - name: dev
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30010

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev
  namespace: default
  labels:
    app: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev
  template:
    metadata:
      labels:
        app: dev
    spec:
      restartPolicy: Always
      containers:
        - name: dev
          imagePullPolicy: IfNotPresent
          image: tuimac/development
          ports:
            - containerPort: 80
