apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::000000000000:role/EC2-EKS-role
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::000000000000:role/EC2-EKS-role
      username: admin
      groups:
        - system:masters
#https://docs.aws.amazon.com/ja_jp/eks/latest/userguide/add-user-role.html
