apiVersion: apps/v1
kind: Deployment
metadata:
  name: httptrackre-deployment
spec:
  selector:
    matchLabels:
      app: httptracker
  replicas: 4
  template:
    metadata:
      labels:
        app: httptracker
    spec:
      containers:
      - name: httptracker
        image: tuimac/httptracker:latest
        ports:
        - containerPort: 8000
